baseURL = "https://cheese-cracker.github.io/"
title = "Futuristic ideas"
copyright = "©2024 cheese-cracker"
theme = "hugo-notepadium-mod"
summaryLength = 30

languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = true

enableRobotsTXT = true
paginate = 5  # The number of articles in per page
enableEmoji = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics (Not supported anymore)
# googleAnalytics = "G-VK520LPFV1"


# [module]
#   [[module.imports]]
#     path = "github.com/qdzhang/hugo-notepadium-mod"  # Use module to use this theme

# Set RSS to Path to "posts" folder in rss.xml file
[outputs]
  home = ["HTML", "RSS"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 1
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 1
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 1
    [minify.tdewolff.xml]
      keepWhitespace = false

# Configure chroma highlight
# Reference https://gohugo.io/content-management/syntax-highlighting/
# https://gohugo.io/getting-started/configuration-markup#highlight
[markup.highlight]
codeFences = true
guessSyntax = false
noClasses = true
style = "dracula"

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[permalinks]
  post = "/posts/:filename/"

[author]
    name = "cheese-cracker"  # Change to your name


[params]
author = "cheese-cracker"
description = "A place for interesting ideas, notes and blogposts"
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
# logo = "/img/cheese-cracker.jpg"
slogan = ""
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."


[params.giscus]
enable = true
repo = "cheese-cracker/cheese-cracker.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkxMzkzMjU3NTU="
category = "Announcements"
categoryID = "DIC_kwDOCE3xO84COSY5"
dataTheme = "dark"
dataLang = "en"

# If you use custom css files, declare them here
[params.assets]
css = ["css/fonts.css", "css/custom.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = true # load math globally, default: false. You can always enable math on per page.
use = "mathjax"  # builtin: "katex", "mathjax".  default: "katex"

[taxonomies]
category = "categories"
tag = "tags"
search = "search"

[[params.nav.custom]]
title = "Home"
url = "/"

[[params.nav.custom]]
title = "Tags"
url = "/tags/"

# [[params.nav.custom]]
# title = "Categories"
# url = "/categories/"

[[params.nav.custom]]
title = "Archives"
url = "/archives/"

[[params.nav.custom]]
title = "Search"
url = "/search/"

[[params.nav.custom]]
title = "About"
url = "/about/"
