[input]
base_directory = "./content/"
url_prefix = "/"
files = [
    {path = "about.md", url = "about", title = "About and Contact Page"},
    {path = "posts/compgeom.md", url = "posts/compgeom", title = "Computational Geometry Notes"},
    {path = "posts/discrete-vs-continuous.md", url = "posts/discrete-vs-continuous", title = "Discrete Vs Continuous Ideas"},
    {path = "posts/graphsnetworks.md", url = "posts/graphsnetworks", title = "Graphs Theory Notes"},
    {path = "posts/mmodelling.md", url = "posts/mmodelling", title = "Math Modelling Notes"},
    {path = "posts/poe.md", url = "posts/poe", title = "Principles of Economics Notes"},
    {path = "posts/numan.md", url = "posts/numan", title = "Numerical Analysis Notes"},
]
